# Generated by Django 4.0 on 2022-01-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DepartmentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('dept', models.ManyToManyField(to='DepartmentApp.Dept')),
            ],
        ),
    ]
